"""init

Revision ID: 87d452681592
Revises: 53f7039df6d1
Create Date: 2025-05-28 18:03:40.308274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87d452681592'
down_revision = '53f7039df6d1'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
